# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Tue Jan  1 15:44:16 PST 2013
#
#/ usage: bamboo:setup [ --bamboo-user <bamboo>] [ --bamboo-password <admin123>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --bamboo-user) rerun_option_check $# ; BAMBOO_USER=$2 ; shift ;;
            --bamboo-password) rerun_option_check $# ; BAMBOO_PASSWORD=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$BAMBOO_USER" ] && BAMBOO_USER="bamboo"
    [ -z "$BAMBOO_PASSWORD" ] && BAMBOO_PASSWORD="admin123"
    # Check required options are set

    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
BAMBOO_USER=
BAMBOO_PASSWORD=


